### ISSUE TITLE
Cannot stringify double-floats in LispWorks 8.0.1

### ISSUE THREAD

**Issue by JensNevens** [Zulu-Inuoe/jzon#55]
Hello,

On LispWorks 8.0.1, I always get an error when trying to `stringify` a double-float.
For example:

```
(jzon:stringify 2.77D3)
=> In LOGBITP of (63 2770.0D0) arguments should be of type INTEGER.
```

**Comment by Zulu-Inuoe** [comment]
Interesting. Looks like there's an issue with `float-features` on LispWorks. Assuming you're using QuickLisp, could you please update your dists `(ql:update-all-dists)`  and see if you still have this issue? Looks like that code was touched around April 2023

**Comment by Gleefre** [comment]
Seems like a bug in float-features to me, see https://github.com/Shinmera/float-features/issues/21.
The fix was pushed but the dependency on `trivial-features` wasn't added; so I *think* that none of the branches in `ff:double-float-bits` were selected and thus the float itself was returned (as a result of `setf`).

Try loading `trivial-features` and then force reload the float-feautres as a workaround?

**Comment by Gleefre** [comment]
You probably should recompile these libraries with `(asdf:load-system ... :force t)` or by deleting the cache folder (somewhere in `~/.cache/common-lisp/lw.../path/to/library`).

For example:
```lisp
CL-USER> (ql:quickload :trivial-features)
To load "trivial-features":
  Load 1 ASDF system:
    trivial-features
; Loading "trivial-features"

(:TRIVIAL-FEATURES)
CL-USER> (asdf:load-system :float-features :force t)
; compiling file ... <several lines>
T
CL-USER> (asdf:load-system :com.inuoe.jzon :force t)
; compiling file ... <several lines>
T
```

Most probably it will be enough to do it once.

**Comment by JensNevens** [comment]
Clearing the cache folder did the trick! Thank you
