### ISSUE TITLE
Is there a way to convert lisp case to camel case?

### ISSUE THREAD

**Issue by daninus14** [Zulu-Inuoe/jzon#60]
Thanks for writing this library!

I'm trying to transition from `cl-json` to `jzon`. I have projects where the javascript keys are all camel case because cl-json maps hyphen case to camel case. 

Is there an option we can pass to jzon to produce camel case json strings for the keys of json objects?

If not, is there a method one can override to achieve this?

**Comment by Zulu-Inuoe** [comment]
Sure.

Are you going CLOS->JSON, or JSON->CLOS?

Currently there's no built-in for JSON->CLOS, which is what #7 is about.

For CLOS->JSON, the options are in in the section [custom serialization](https://github.com/Zulu-Inuoe/jzon?tab=readme-ov-file#custom-serialization). specifically the section about [specializing coerced-fields](https://github.com/Zulu-Inuoe/jzon?tab=readme-ov-file#specializing-coerced-fields)

You can either specialize that for each of your classes, or, if your classes all have a common parent class, you can do something like this:

```lisp
(defclass foo ()
  ((a-field :initarg :a)
   (besides-this :initarg :b)
   (cant-hurt :initarg :c)))

;; The default method:
(jzon:coerced-fields (make-instance 'foo :a "hello" :b "world")) #| => ((A-FIELD "hello" T) (BESIDES-THIS "world" T)) |#

;; Our specialization
(defmethod jzon:coerced-fields ((obj foo))
  (let* ((fields (call-next-method))
           (fields (mapcar (lambda (f) (cons (cffi:translate-camelcase-name (car f)) (cdr f))) fields)))
    fields))

;; Now
(jzon:coerced-fields (make-instance 'foo :a "hello" :b "world")) #| => (("aField" "hello" T) ("besidesThis" "world" T)) |#
```

Any child class of `foo` will use this method, so you should get camel-case without having to write a method per class.
FYI here I used `cffi:translate-camelcase-name` just because it's the first thing that came to mind. You probably want to use something else

**Comment by daninus14** [comment]
Thank you so much! This is great! Yeah, CLOS to JSON.

I was about to close the issue, but I feel like it should be visible to people searching for the docs. Would you consider just adding a second coerced-fields example and simply copy pasting your explanation with the title `Example: Changing Field Names From Hyphen Case to Camel Case`?

Thank you again so much for the help!

**Comment by Zulu-Inuoe** [comment]
An examples section sounds like a good idea, thank you
